name: Oxyra Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build_frontend:
    name: 🏗️ Construir Frontend en GitHub
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependencias del Frontend
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Compilar Frontend (Vite)
        working-directory: ./frontend
        run: npm run build

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: frontend/dist

  deploy_frontend:
    name: 🚀 Deploy Frontend al VPS
    needs: build_frontend
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Subir dist al VPS
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "187.33.145.101"
          REMOTE_USER: "Jordi"
          REMOTE_PORT: "2222"
          TARGET: "/var/www/html/Oxyra/frontend/dist"

  deploy_backend:
    name: 🔧 Deploy Backend al VPS
    needs: build_frontend
    runs-on: ubuntu-22.04

    steps:
      - name: Ejecutar deploy backend por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP }}
          port: 2222
          username: Jordi
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/html/Oxyra/backend
            git pull origin main

            npm install --production

            pm2 reload all || pm2 restart all